# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: 'true'
      show-details: always
  security:
    enabled: 'false'
spring:
  boot:
    admin:
      client:
        instance:
          prefer-ip: 'true'
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        auto-registration: 'true'
        url: http://localhost:8080
        username: admin
        password: admin
        enabled: 'true'
  security:
    user:
      password: client1
      name: client1
